### PR TITLE
Added prefixes and live-convert

### PR DESCRIPTION
**Pull request by ksaweryr**
Added live-convert and unit prefixes for both sides. Updated description of falcon
screen

### CODE REVIEW

**Comment by makoteq** [comment]
Please provide link with Demo

**Comment by ksaweryr** [comment]
http://46.101.224.64/sasinator.html

You could just download index.html and open it in any browser

**Review by makoteq — APPROVED** [review]
LGTM!

**Comment by ksaweryr** [comment]
@Faust-o co sądzisz?

**Pull request merged**
